---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  JenkinsRole:
    Type: String
Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AWS::StackName}-sample
